name: deploy_on_firebase

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy

        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID : ${{ secrets.PROJECT_ID }}
